apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
spec:
  kafkaRest:
    authentication:
      type: bearer
      bearer:
        secretRef: mds-kafka
    tls:
      secretRef: tls-kafka
  
  kafkaClusterRef:
    name: kafka
