# Default pipeline from cli
steps:
- label: ":one-does-not-simply: Build :wrench:"
  commands:
    - kustomize build ps-cfk-infra/environments/gke/0_dev/with_prometheus;
    - kustomize build --enable-helm ps-cfk-infra/environments/rbac_ingress_init/with_observability/prometheus
  plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.4


