#!/bin/sh

echo 'Configuring Oracle for user myuser'

# Set archive log mode and enable GG replication
ORACLE_SID=ORCLCDB
export ORACLE_SID



sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLPDB1 << EOF
create table CUSTOMERS (
     id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 42) NOT NULL PRIMARY KEY,
     first_name VARCHAR(50),
     last_name VARCHAR(50),
     email VARCHAR(50),
     gender VARCHAR(50),
     club_status VARCHAR(20),
     comments VARCHAR(90),
     create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
     update_ts timestamp
);
CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_UPD
BEFORE INSERT OR UPDATE ON CUSTOMERS
REFERENCING NEW AS NEW_ROW
FOR EACH ROW
BEGIN
SELECT SYSDATE
     INTO :NEW_ROW.UPDATE_TS
     FROM DUAL;
END;
/
insert into CUSTOMERS (id, first_name, last_name, email, gender, club_status, comments) values (1, 'Rica', 'Blaisdell', 'rblaisdell0@rambler.ru', 'Female', 'bronze', 'Universal optimal hierarchy');
insert into CUSTOMERS (id, first_name, last_name, email, gender, club_status, comments) values (2, 'Ruthie', 'Brockherst', 'rbrockherst1@ow.ly', 'Female', 'platinum', 'Reverse-engineered tangible interface');
insert into CUSTOMERS (id, first_name, last_name, email, gender, club_status, comments) values (3, 'Mariejeanne', 'Cocci', 'mcocci2@techcrunch.com', 'Female', 'bronze', 'Multi-tiered bandwidth-monitored capability');
insert into CUSTOMERS (id, first_name, last_name, email, gender, club_status, comments) values (4, 'Hashim', 'Rumke', 'hrumke3@sohu.com', 'Male', 'platinum', 'Self-enabling 24/7 firmware');
insert into CUSTOMERS (id, first_name, last_name, email, gender, club_status, comments) values (5, 'Hansiain', 'Coda', 'hcoda4@senate.gov', 'Male', 'platinum', 'Centralized full-range approach');
CREATE TABLE REGIONS (
     region_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 5 PRIMARY KEY,
     region_name VARCHAR2( 50 ) NOT NULL,
     comments VARCHAR(90),
     create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
     update_ts timestamp
);
CREATE OR REPLACE TRIGGER TRG_REGIONS_UPD
BEFORE INSERT OR UPDATE ON REGIONS
REFERENCING NEW AS NEW_ROW
FOR EACH ROW
BEGIN
SELECT SYSDATE
     INTO :NEW_ROW.UPDATE_TS
     FROM DUAL;
END;
/
CREATE TABLE COUNTRIES (
    country_id   CHAR( 2 ) PRIMARY KEY  ,
    country_name VARCHAR2( 40 ) NOT NULL,
    region_id    NUMBER                 , -- fk
    comments VARCHAR(90),
    create_ts timestamp DEFAULT CURRENT_TIMESTAMP ,
    update_ts timestamp ,
    CONSTRAINT fk_COUNTRIES_REGIONS FOREIGN KEY( region_id )
    REFERENCES REGIONS( region_id )
       ON DELETE CASCADE
);
CREATE OR REPLACE TRIGGER TRG_COUNTRIES_UPD
BEFORE INSERT OR UPDATE ON COUNTRIES
REFERENCING NEW AS NEW_ROW
FOR EACH ROW
BEGIN
SELECT SYSDATE
     INTO :NEW_ROW.UPDATE_TS
     FROM DUAL;
END;
/

insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (1, 'EUROPE', 'EU');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (2, 'SOUTHWEST', 'AIRLINES');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (3, 'MIDWEST', 'USA');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (4, 'AFRICA', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (5, 'NORTHWEST', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (6, 'EASTWEST', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (7, 'KANKAKEE', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (8, 'SOUTHEAST', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (9, 'NORTHEAST', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (10, 'NORTHWEST', 'A+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (11, 'KENTUCKY', 'KFC+');
insert into REGIONS (REGION_ID, REGION_NAME, COMMENTS) VALUES (12, 'ASIA', 'A+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('AR','Argentina',12, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('AU','Australia',10, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('BE','Belgium',1, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('BR','Brazil',2, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('CA','Canada',11, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('CH','Switzerland',1, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('CN','China',3, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('DE','Germany',1, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('DK','Denmark',5, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('EG','Egypt',4, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('FR','France',8, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('IL','Israel',9, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('IN','India',3, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('IT','Italy',1, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('JP','Japan',3, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('KW','Kuwait',4, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('ML','Malaysia',3, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('MX','Mexico',2, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('NG','Nigeria',4, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('NL','Netherlands',1, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('SG','Singapore',7, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('UK','United Kingdom',6, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('US','United States of America',2, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('ZM','Zambia',11, 'B+');
insert into COUNTRIES (COUNTRY_ID,COUNTRY_NAME,REGION_ID, COMMENTS) values ('ZW','Zimbabwe',4, 'B+');
exit;
EOF