{
 "title": "Confluent Platform overview",
 "description": "Overview of the main health-check metrics from Confluent Platform components.",
 "tags": [
  "confluent",
  "kafka",
  "zookeeper",
  "kafka-connect",
  "schema-registry",
  "ksqldb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "connect_cluster",
    "label": "Kafka Connect cluster",
    "query": "label_values(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$env\"}, app)"
   },
   {
    "name": "ksqldb_cluster",
    "label": "ksqlDB cluster",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{namespace=\"$env\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZK: Quorum Size",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble.\n            Count Zookeeper servers with quorum size metric.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: ZNodes (avg.)",
   "type": "stat",
   "description": "Average size of ZNodes in the cluster.\n            Getting the node count per server, and averaging the node count.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Connections used",
   "type": "stat",
   "description": "Sum of the number of alive connections per servers divided by the maximum number of client connections allowed per host.\n            If the percentage is higher than 60%, then Zookeeper should be scaled and/or the Zookeeper clients should be investigated to find the reason for high number of connections opened.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zookeeper_numaliveconnections{namespace=\"$env\"} / zookeeper_maxclientcnxnsperhost{namespace=\"$env\"}"
    }
   ]
  },
  {
   "title": "ZK: Sum of watchers",
   "type": "stat",
   "description": "Sum of client watchers subscribed to changes on the ZNodes.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "ZK: Outstanding Requests",
   "type": "timeseries",
   "description": "Number of requests waiting for processing (queued).\n            If the number of outstanding requests grows higher than 10, then the Zookeeper hosts should be checked.\n            It could mean that there is not enough resources to cope with the number of requests.\n            ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{namespace=\"$env\"}",
     "legendFormat": "{{pod}} ({{server_id}}:{{member_type}})"
    }
   ]
  },
  { "title": "Kafka cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Kafka: Online Brokers",
   "type": "stat",
   "description": "Count of brokers available (online).\n            This value is referential and should not be used for alerting.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Active Controller",
   "type": "stat",
   "description": "Active Controller broker.\n            It should always be 1. If the value is different than 1, then it must be alerted for troubleshooting.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$env\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Partitions",
   "type": "stat",
   "description": "Sum of Topic partitions across the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Under-Replicated Partitions (URP)",
   "type": "stat",
   "description": "Sum of Under-Replicated Partitions. This is caused by broker or volumes unavailable, impacting replicas to be offline, and reducing the ISR set for those partitions.\n            There are transient scenarios that could lead to this number growing (e.g. broker restart), but if the number doesn't shrink in a short period of time (e.g. 1 minute), then it's recommended to alert.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Under-MinISR Partitions",
   "type": "stat",
   "description": "Number of partitions where the number of replicas offline is higher than the minimum ISR configuration.\n            This means partitions are not available for Producers with acks=all.\n            It's recommended alerting when this values is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "Kafka: Sum of Offline Partitions",
   "type": "stat",
   "description": "Number of partitions where all replicas are offline.\n            Producers and Consumers are affected by this condition.\n            It's recommended alerting when this values is higher than 0.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$env\"})"
    }
   ]
  },
  { "title": "Schema Registry cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "SR: Online instances",
   "type": "stat",
   "description": "Schema Registry online instances returning metrics.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Registered Schemas (avg.)",
   "type": "stat",
   "description": "Average number of registered schemas across the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Schemas Created by Type (avg.)",
   "type": "stat",
   "description": "Average number of schemas created, by type.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_schemas_created{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "SR: Schemas Deleted by Type (avg.)",
   "type": "stat",
   "description": "Average number of schemas deleted, by type.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "Kafka Connect cluster: $connect_cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "connect_cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Connect: Online Workers",
     "type": "stat",
     "description": "Kafka Connect online workers returning metrics.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kafka_connect_connect_worker_metrics_connector_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Total Tasks",
     "type": "stat",
     "description": "Number of tasks deployed on Kafka Connect cluster.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Running Tasks",
     "type": "stat",
     "description": "Number of Running Tasks on the Kafka Connect cluster.\n            Ideally, this number should be equal to the total number of tasks deployed.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Paused Tasks",
     "type": "stat",
     "description": "Number of Paused Tasks on the Kafka Connect cluster.\n            Ideally, this number should be zero, as tasks should be running.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Failed Tasks",
     "type": "stat",
     "description": "Number of Paused Tasks on the Kafka Connect cluster.\n            Ideally, this number should be zero, as tasks should be running.\n            It's recommended alerting when this value is higher than 0.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{namespace=\"$env\",app=~\"$connect_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Time since last rebalance",
     "type": "stat",
     "description": "Informative value. Time since last rebalance.\n            When this value is continuously and repeatedly low means some connectors are failing and rebalancing is triggered constantly.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "clockms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{namespace=\"$env\",app=~\"$connect_cluster\"} >= 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ksqlDB cluster: $ksqldb_cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "ksqldb_cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "ksqlDB: Online instances",
     "type": "stat",
     "description": "ksqlDB online instances returning metrics.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Active Queries",
     "type": "stat",
     "description": "Number of active queries deployed in the cluster.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_num_active_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Running Queries",
     "type": "stat",
     "description": "Number of running queries deployed in the cluster.\n            Ideally, this number should be equal to the number of active queries as queries should be running.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_running_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "ksqlDB: Sum of Rebalancing Queries",
     "type": "stat",
     "description": "Number of queries rebalancing in the cluster.\n            Ideally, this number should be equal zero, or return to zero in a short period (e.g. 1 minute).\n            It's recommended to alert if the number of rebalancing queries stay higher than 0 for a longer period of time.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"})"
      }
     ]
    },
    {
     "title": "Connect: Sum of Queries Failed",
     "type": "stat",
     "description": "Number of queries failed in the cluster.\n            Ideally, this number should be equal zero.\n            It's recommended to alert if the number of queries failed is higher than 0.\n            ",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(ksql_ksql_engine_query_stats_error_queries{namespace=\"$env\",app=\"$ksqldb_cluster\"})"
      }
     ]
    }
   ]
  }
 ]
}