{
 "title": "Kafka Quotas",
 "description": "Overview of the Kafka quotass",
 "tags": [
  "confluent",
  "kafka-client",
  "kafka-quota"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_server_produce_byte_rate{namespace=\"$env\"},pod)"
   },
   { "name": "user", "label": "User", "query": "label_values(user)" },
   { "name": "client_id", "label": "Client ID", "query": "label_values(client_id)" }
  ]
 },
 "panels": [
  {
   "title": "Produce Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_produce_byte_rate{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"})",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_fetch_byte_rate{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"})",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_request_request_time{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"})",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  },
  {
   "title": "Produce Throttle Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_produce_throttle_time{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"} > 0)",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Throttle Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_fetch_throttle_time{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"} > 0)",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  },
  {
   "title": "Request Throttle Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,kafka_server_request_throttle_time{namespace=\"$env\",user=~\"$user\",client_id=~\"$client_id\",pod=~\"$broker\"} > 0)",
     "legendFormat": "User:{{user}} | Client ID:{{client_id}} @ Broker:{{pod}}"
    }
   ]
  }
 ]
}