{
 "title": "Schema Registry cluster",
 "description": "Overview of the Schema Registry cluster",
 "tags": [
  "confluent",
  "schema-registry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(namespace)" },
   {
    "name": "sr_server",
    "label": "Server",
    "query": "label_values(kafka_schema_registry_registered_count{namespace=\"$env\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SR: Online instances",
   "type": "stat",
   "description": "Schema Registry online instances returning metrics.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Registered Schemas (avg.)",
   "type": "stat",
   "description": "Average number of registered schemas across the cluster.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_registered_count{namespace=\"$env\"})"
    }
   ]
  },
  {
   "title": "SR: Created Schemas by Type (avg.)",
   "type": "stat",
   "description": "Average number of schemas created, by type.\n            ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_schema_registry_schemas_created{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "SR: Sum of Deleted Schemas by Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_schemas_deleted{namespace=\"$env\"}) by (schema_type)",
     "legendFormat": "{{schema_type}}"
    }
   ]
  },
  {
   "title": "SR: Sum of Active Connections",
   "type": "stat",
   "description": "Number of active connections",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_schema_registry_kafka_schema_registry_metrics_connection_count{namespace=\"$env\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$env\",pod=\"$sr_server\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{namespace=\"$env\",pod=\"$sr_server\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(irate(jvm_gc_collection_seconds_sum{namespace=\"$env\",pod=\"$sr_server\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kafka_schema_registry_kafka_schema_registry_metrics_connection_count{namespace=\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_rate{namespace=\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_latency_99{namespace=\"$env\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}